name: Spec MDBook CD

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Download mdbook build artifact ğŸ“¦
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mdbook_ci.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          check_artifacts:  true

      - name: Decompress mdbook build artifact ğŸ“¦
        run: mkdir book && tar -xvf spec_mdbook-${{ github.sha }}/spec_mdbook.tar ./book && ls ./book

      - name: Deploy mdBook to github pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
