name: Spec MDBook CD

on:
  push:
    tags: 
      - '^\d{8}\.\d+'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Download mdbook build artifact ğŸ“¦
        uses: actions/download-artifact@v3
        with:
          name: spec_mdbook-${{github.sha}}
          path: spec_mdbook.tar

      - name: Decompress mdbook build artifact ğŸ“¦
        run: tar -xvf spec_mdbook.tar ./book

      - name: Deploy mdBook to github pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          folder: ./book
