name: Spec MDBook CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ğŸ°
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install ğŸ’¾
        run: npm install

      - name: Lint and Spellcheck ğŸ§¶
        run: npm run lint
      
      - name: Setup mdbook and build dsnp spec book ğŸ“š
        uses: drmingdrmer/mdbook-full@main
        
      - name: Build dsnp spec book ğŸ“š
        run: mdbook build

      - name: Create tarball ğŸ“¦
        run: tar -cvf spec_mdbook.tar ./book

      - name: Create mdbook build artifact ğŸ“¦
        uses: actions/upload-artifact@v3
        with:
          name: spec_mdbook
          path: spec_mdbook.tar

      #- name: Deploy mdBook to github pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./book
