name: Spec MDBook CI

on:
  push:
    branches: [main]
  create:
    tags: 
      - "^\d{8}\.\d+"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ğŸ°
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.3'

      - name: Update npm to v7 ğŸ”¼
        run: npm i -g npm

      - name: Install ğŸ’¾
        run: npm install

      - name: Lint ğŸ§¶
        run: npm run lint
      
      - name: Remark ğŸ“
        run: npm run lint-md
      
      - name: Spellcheck ğŸ§™â€â™‚ï¸
        run: npm run spellcheck

      - name: Setup mdbook and build dsnp spec book ğŸ“š
        uses: drmingdrmer/mdbook-full@main
        
      - name: Build dsnp spec book ğŸ“š
        run: mdbook build

      - name: Create mdbook build artifact ğŸ“¦
        uses: actions/upload-artifact@v3
        with:
          name: spec_mdbook
          path: |
            book

      - name: Deploy mdBook to github pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        # check tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          branch: gh-pages
          folder: ./book
