name: Spec MDBook CD

on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Download mdbook build artifact ğŸ“¦
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: mdbook_ci.yml
          workflow_conclusion: success
          commit: ${{github.sha}}
          check_artifacts:  true

      - name: Decompress mdbook build artifact ğŸ“¦
        run: mkdir book && tar -xvf spec_mdbook.tar ./book && ls ./book

      # - name: Deploy mdBook to github pages ğŸš€
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     folder: ./book
